# Travis CI for https://travis-ci.com/endiliey/endiliey.github.io/

language: node_js
node_js:
  - '8'

branches:
  only:
    - source
    
cache:
  yarn: true

notifications:
  email: true

script:
  - yarn install

before_deploy:
  - yarn run build

deploy:
  provider: pages
  github_token: $GH_TOKEN
  skip_cleanup: true
  local-dir: build
  on:
    branch: source