# Travis CI for https://travis-ci.com/endiliey/endiliey.github.io/

language: node_js
node_js:
  - 8

script:
  - yarn run build

deploy:
  provider: pages
  github_token: $GH_TOKEN
  skip_cleanup: true
  local-dir: build
  keep-history: true
  target_branch: master
  on:
    branch: source