# Travis CI for https://travis-ci.com/endiliey/endiliey.github.io/

language: node_js
node_js:
  - '8'

branches:
<<<<<<< HEAD
  ignore:
    - gh-pages

=======
  only:
    - source
    
>>>>>>> 8bf8f6543907ba3d9053d0a472bbb408f537044a
cache:
  yarn: true

notifications:
  email: true

env:
  matrix:
    - TEST_TYPE=build_website

script:
- |
  if [ "$TEST_TYPE" != build_website ]
  then
    yarn run $TEST_TYPE
  else
    set -e
    ./node_modules/.bin/gulp
    if [ "$TRAVIS_PULL_REQUEST" = false ] && [ "$TRAVIS_BRANCH" = ${GH_BRANCH} ]; then
      # Automatically publish the website
      git config --global user.name "${GH_NAME}"
      git config --global user.email "${GH_EMAIL}"
      echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
      cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
    else
      # Make sure the website builds without error
    if [ "$TRAVIS_PULL_REQUEST" = false ]; then
      # Configure git user & setup
      echo "Publishing ..."
      git config --global user.name "${GH_NAME}"
      git config --global user.email "${GH_EMAIL}"
      echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
      cd website && yarn install && yarn run write-translations && cd ..
      # install Crowdin
      sudo apt-get install default-jre
      wget https://artifacts.crowdin.com/repo/deb/crowdin.deb -O crowdin.deb
      sudo dpkg -i crowdin.deb
      # upload translation strings and download translations
      cd website
      CROWDIN_DOCUSAURUS_PROJECT_ID="${CROWDIN_ID}" CROWDIN_DOCUSAURUS_API_KEY="${CROWDIN_API}" yarn run crowdin-upload
      CROWDIN_DOCUSAURUS_PROJECT_ID="${CROWDIN_ID}" CROWDIN_DOCUSAURUS_API_KEY="${CROWDIN_API}" yarn run crowdin-download
      # publish
      GIT_USER="${GH_NAME}" yarn run publish-gh-pages
    else
      # Make sure the website builds without error
      echo "Builds .."
      cd website && yarn install && yarn build
    fi
  fi